### ISSUE TITLE
Homepage Chore Checklist

### ISSUE THREAD

**Issue by radium-v** [microsoft/fast#3076]
This issue is intended to hold chores and minor bugfixes/best practice nudges for the new homepage before we go live.

- Meta:
  - [ ] Favicon (#3388)
  - [ ] title and description
- Background:
  - [x] Background should dim further after scrolling past the hero
- Navbar:
  - [x] **Logo link is redundant - this page should not navigate to itself**
  - [x] text links should be darker at rest
  - [x] Logo text should be SVG (#3355)
  - [x] Github logo should be the accent
  - [x] non-mobile breakpoints should have same alignment style (logo on left, links in center, github link on right)(#3344)
- Section indicator:
  - [x] Items shouldn't be clickable (#3338)
- All Sections:
  - [x] **Add Activ Grotesque - Chris has CDN link and values** (#3368)
  - [x] **Reduce height of each module**
  - [x] `.section-badge` should have: (#3296)
  - [x] more letter spacing (#3296)
  - [x] black background (#3296)
  - [x] rounded corners (#3296)
  - [x] `<site-section-header>`s should constrain width at non-mobile breakpoints (#3347)
  - [x] Increase margin between paragraphs and buttons (#3296)
- Hero Section:
  - [ ] "Get Started" button has no link
  - [x] paragraph text should be larger (#3296)
- Adaptive UI Section:
  - [ ] Frame width causes other sections to overflow at middle breakpoints
  - [ ] "Explore components" button has no link
  - [ ] card bg not updating when dark mode toggled or bg color value updated
  - [ ] Hue and saturation sliders missing track styles
- Frameworks section:
  - [ ] "Learn More" button has no link
  - [x] **Add backplate to match features** (#3366)
  - [x] **Add transition to backplate** (#3366)
- Features section:
  - [x] **Drop the hand on hover as these are not clickable** (#3363)
  - [x] **Add transition to backplate** (#3366)
  - [x] **Grey text using filter should shift to opacity. Grey looks muddy.** (#3366)
  - [ ] "Read documentation"
  - [x] Each card should also use `:focus-within` to set background color for visibility when using  keyboard navigation(#3284)
  - [ ] Every anchor needs a link
- Community section:
  - [x] Each card should also use `:focus-within` to set background color for visibility when using keyboard navigation (#3284)
- Footer:
  - [x] Missing divider line (#3346)
  - [x] text links should be darker at rest (#3346)

**Comment by khamudom** [comment]
responsive

**Comment by SamanthaAO** [comment]
working on badge styling

**Comment by radium-v** [comment]
> Logo link is redundant - this page should not navigate to itself

Redundancy or not, this is common practice for 99% of websites in existence.

**Comment by EisenbergEffect** [comment]
@radium-v Are we able to close this out now?

**Comment by chrisdholt** [comment]
@EisenbergEffect, I would close this - any new work should be new issues as we've launched the homepage. This checklist was intended to track work related to the launch.
