### ISSUE TITLE
Launch FAST

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast#3307]
An ordered checklist of what we need to do to launch FAST:

* [x] Merge @radium-v's homepage/docs integration PR #3311
* [x] Merge @radium-v's content load timing fix PR #3367
* [x] Merge @chrisdholt's site ui fixes #3324 
* [x] @awentzel to implement pipeline updates to deploy both www and explore sites #3322
* [x] Merge @awentzel path correction PR #3328 
* [x] Merge @awentzel's docs fixes PR #3329 
* [x] Merge @radium-v's background dim PR #3333
* [x] Merge @SamanthaAO 's site badge fix
* [x] Merge @chrisdholt's internal part name PR #3306
* [x] Merge @chrisdholt's anchor style fixes #3320
* [x] Merge @chrisdholt's ui regression fixes #3327
* [x] Merge @chrisdholt's hyptertext fixes #3319 
* [x] Merge @chrisdholt button height fix #3340
* [x] Merge @eisenbergeffect's missing elements export fix #3331 
* [x] Merge @eisenbergeffect's style flexibility fix #3345 
* [x] Merge @SethDonohue tabs fix #3350 
* [x] Merge @nicholasrice's upcoming docs PRs #3316 #3321
* [x] Merge @nicholasrice's fast-components-msft API docs PR #3332 
* [x] Merge @nicholasrice 's color parsing export fix #3356 
* [x] Merge @nicholasrice's home page link fixes #3362 
* [x] Merge @nicholasrice 's animation and colors API docs #3359
* [x] Merge @janechu's PR for the logo #3313
* [x] Merge @janechu's upcoming PR for creating absolute paths in the guidance section #3325
* [x] Merge @EisenbergEffect's children directive fix and filter feature #3323 
* [x] Merge @EisenbergEffect's event capture bug fix #3337 
* [x] Merge @EisenbergEffect's big docs PR #3315
* [x] Merge @EisenbergEffect's grammar and style PR #3354 
* [x] Merge @EisenbergEffect's faq header normalization PR #3364
* [x] Merge @nicholasrice's light mode logo and theme switcher for docs PR #3380
* [x] Merge @EisenbergEffect PR to update docs with new repo name #3381
* [x] Rename the repo to "fast"
* [ ] Publish all web components packages
* [ ] Create Permanent Redirect from old site to new site for URLs that have changed.
* [ ] Publish the website
* [ ] Publish the Component Explorer

**Comment by EisenbergEffect** [comment]
Ping @awentzel. The homepage/docs integration is now merged. So, I believe you can proceed with the pipeline updates.

**Comment by chrisdholt** [comment]
@EisenbergEffect I was rolling through this and noticed the following:

>  URLs pointing to external resources (non fast.design pages) should open in external window/tab via "_blank" attribute improved SEO and keeping people on our site.

I think we should scratch this in favor of providing the user the opportunity to open whatever external link they want either in the browser or outside of it. I have concerns about usurping their choice in favor of us prioritizing keeping our content open in a window. There's a ton of quick ways to navigate around the web and many users have preference on when and how they manage their tabs/windows. In certain cases this makes sense, such as when you have links as part of active forms or sites where editing is taking place. In those cases navigation could zero out changes being made and opening links in new tabs/windows makes sense. Outside of that though, I don't see a reason to shift from the default behavior of allowing users to open tabs however they prefer.

**Comment by EisenbergEffect** [comment]
I didn't add that particular line-item. So, no disagreement from me. Maybe @awentzel had some thoughts?
In terms of the Markdown, it's just a normal Markdown link. I didn't alter any behavior from the default.

**Comment by chrisdholt** [comment]
> I didn't add that particular line-item. So, no disagreement from me. Maybe @awentzel had some thoughts?
> In terms of the Markdown, it's just a normal Markdown link. I didn't alter any behavior from the default.

For now I've removed the following:
> * [ ] URLs pointing to external resources (non fast.design pages) should open in external window/tab via "_blank" attribute improved SEO and keeping people on our site.

I'm open to discussing the above in an issue if people are passionate. For now, I don't think there is consensus on that functionality/behavior. I also don't think it's required for launch.

**Comment by EisenbergEffect** [comment]
@awentzel There's an item above labeled "Implement and merge review feedback from @awentzel from feature branch into master" Was that tracking your early feedback on the docs (already incorporated) or is that something else we still need to do?

**Comment by EisenbergEffect** [comment]
Ping @awentzel for feedback on the above.

**Comment by chrisdholt** [comment]
@eisenbereffect Once we fill out the above, we are good to go. Site is ready for initial publish (yay continuous integration 😄). I believe the component explorer is ready. We can publish as needed. I think we have what we need to close this out!
