### ISSUE TITLE
feat: add fast-benchmark

### ISSUE THREAD

**Issue by prudepixie** [microsoft/fast#5845]
# 🙋 Feature Request

Add fast-benchmark, a performance testing infrastructure to support local development and general benchmarking purposes for FAST libraries.

## 💁 Possible Solution

The main tool to use to run the benchmarks locally will be tachometer, it is a tool used widely for benchmarking known low-level libraries, such as [lit](https://github.com/lit/lit) and [preact](https://github.com/preactjs/preact).
https://github.com/Polymer/tachometer
https://www.npmjs.com/package/tachometer

After some research, my thoughts are to have support for both:
1)  static tests: integrate Krausest tests from https://github.com/krausest/js-framework-benchmark as 'default testing suite', mirroring what [preact](https://github.com/preactjs/preact) has opted for, they only have a single library, so makes sense to reuse the same benchmarks
2) custom tests: this is the direction [lit](https://github.com/lit/lit) went for, since they have multiple libraries (lit-element, lit-html.etc) that is similar to the FAST monorepo, they have opted to write customizable test for different scenarios 

For FAST, it will be ideal to have both, if users don't want to invest in writing custom tests, but still want to do a sanity check, static tests could be a quick way to check for performance gains/loss. Both are good candidates to include in the CI/CD pipeline.

## ✅  Implementation Checklist

- [x] https://github.com/microsoft/fast/issues/5792
- [x] https://github.com/microsoft/fast/issues/5842
- [x] https://github.com/microsoft/fast/issues/5841
- [x] https://github.com/microsoft/fast/issues/5918
- [ ] https://github.com/microsoft/fast/issues/5843
- [x] https://github.com/microsoft/fast/issues/5844

## 💻 Examples
Example test result for different versions of fast-element run with Tachometer (for context, this was a run on memory usage, tracked by window.usedJSHeapSize):

<img width="876" alt="Screen Shot 2022-04-14 at 11 00 20 AM" src="https://user-images.githubusercontent.com/6309989/163452881-e5d4cf8c-e9f1-4f2f-b07d-136d7f57c6ab.png">
